/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppAcademicIndexRouteImport } from './routes/app.academic.index'
import { Route as AppAcademicIdRouteImport } from './routes/app.academic.$id'
import { Route as AppClubsIndexRouteImport } from './routes/app.clubs.index'
import { Route as AppClubsIdRouteImport } from './routes/app.clubs.$id'
import { Route as AppOpportunitiesIndexRouteImport } from './routes/app.opportunities.index'
import { Route as AppOpportunitiesIdRouteImport } from './routes/app.opportunities.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicIndexRoute = AppAcademicIndexRouteImport.update({
  id: '/academic/',
  path: '/academic/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicIdRoute = AppAcademicIdRouteImport.update({
  id: '/academic/$id',
  path: '/academic/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsIndexRoute = AppClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsIdRoute = AppClubsIdRouteImport.update({
  id: '/clubs/$id',
  path: '/clubs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIndexRoute = AppOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/teams': typeof AppTeamsRoute
  '/app/': typeof AppIndexRoute
  '/app/academic/$id': typeof AppAcademicIdRoute
  '/app/clubs/$id': typeof AppClubsIdRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/app/academic/': typeof AppAcademicIndexRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/opportunities/': typeof AppOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/teams': typeof AppTeamsRoute
  '/app': typeof AppIndexRoute
  '/app/academic/$id': typeof AppAcademicIdRoute
  '/app/clubs/$id': typeof AppClubsIdRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/app/academic': typeof AppAcademicIndexRoute
  '/app/clubs': typeof AppClubsIndexRoute
  '/app/opportunities': typeof AppOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/teams': typeof AppTeamsRoute
  '/app/': typeof AppIndexRoute
  '/app/academic/$id': typeof AppAcademicIdRoute
  '/app/clubs/$id': typeof AppClubsIdRoute
  '/app/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/app/academic/': typeof AppAcademicIndexRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/opportunities/': typeof AppOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/teams'
    | '/app/'
    | '/app/academic/$id'
    | '/app/clubs/$id'
    | '/app/opportunities/$id'
    | '/app/academic/'
    | '/app/clubs/'
    | '/app/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/teams'
    | '/app'
    | '/app/academic/$id'
    | '/app/clubs/$id'
    | '/app/opportunities/$id'
    | '/app/academic'
    | '/app/clubs'
    | '/app/opportunities'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/teams'
    | '/app/'
    | '/app/academic/$id'
    | '/app/clubs/$id'
    | '/app/opportunities/$id'
    | '/app/academic/'
    | '/app/clubs/'
    | '/app/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academic/': {
      id: '/app/academic/'
      path: '/academic'
      fullPath: '/app/academic/'
      preLoaderRoute: typeof AppAcademicIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academic/$id': {
      id: '/app/academic/$id'
      path: '/academic/$id'
      fullPath: '/app/academic/$id'
      preLoaderRoute: typeof AppAcademicIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/': {
      id: '/app/clubs/'
      path: '/clubs'
      fullPath: '/app/clubs/'
      preLoaderRoute: typeof AppClubsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/$id': {
      id: '/app/clubs/$id'
      path: '/clubs/$id'
      fullPath: '/app/clubs/$id'
      preLoaderRoute: typeof AppClubsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities/': {
      id: '/app/opportunities/'
      path: '/opportunities'
      fullPath: '/app/opportunities/'
      preLoaderRoute: typeof AppOpportunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities/$id': {
      id: '/app/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/app/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppTeamsRoute: typeof AppTeamsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAcademicIdRoute: typeof AppAcademicIdRoute
  AppClubsIdRoute: typeof AppClubsIdRoute
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
  AppAcademicIndexRoute: typeof AppAcademicIndexRoute
  AppClubsIndexRoute: typeof AppClubsIndexRoute
  AppOpportunitiesIndexRoute: typeof AppOpportunitiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTeamsRoute: AppTeamsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAcademicIdRoute: AppAcademicIdRoute,
  AppClubsIdRoute: AppClubsIdRoute,
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
  AppAcademicIndexRoute: AppAcademicIndexRoute,
  AppClubsIndexRoute: AppClubsIndexRoute,
  AppOpportunitiesIndexRoute: AppOpportunitiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
